### Huilen
GET https://localhost:7145/antwerpen/api/Panels/1 HTTP/1.1
Accept: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8N4jcPeQckxJqWAT-dVO2w1No_gbIBdJgGMF2ojKAJ-wTeJhsFKT_q-6BQaQYbHxzmsibcDpQlKr3SnlEnnp5Zei7LLRRkhki47ISxu_8WqOoIOcgi9Ga1epe6-WJn6o8kI4CoyezHdmQg1EUaPPTBAwkLgWXMCTcQXbmUkQd0bYUVldOyhjD5a30ZXKyzljPilGCp8v7q6OifxIL__u_EDw8murgX-XDedoYaRXuUGh4KrxowBlQUx156LlGTHNGpYzp1Vp_nJjSZfX4R1nMIuth2o5BkOA5BNyrZRltx20G5AyAdO0WRC7PqxdV-2iDmIawzPmnjiceKBcAmmKpLgNr2zSC9Ut805uzmmLIKkgedeGBJ6pbJRiyacO68HEveJzmmNr9-Mk3fBsUPAjYqnjtNMDZAkfxQBa-3eKf_MOgZLLoSgzw-NDiKRqpzPaURaEG03v9zcVBn8vHvw1ERcXN8r1BL18XNypMvXi0KlSvqL4HdeSJ-uWtaR2Olwht_EO4VngSznJnDRAm2Pn4lbfqXRDThxin6Dgv115N81w96irPejug6Aff3Cb48uLZvowqz2Ik21QXvSVEoRJnfLoZd19qYKRDAdKoygOI7lafTWq0WbU7vBAfzWOrleBvTrmgRTORehiSxpZBO5jFtGXfKNA0nLd6jZvT1qUUFN2uYFS-POiRRahGJ6brN53UpD6KZ3KNOXPzRPUjLGksiB4xpwHP5hIcKj_mKcY9xfXBt5n5cBEMqYuiL6Xc4R8ygmmQxwWpQd6r28qWqWAVv3eIuLkYWtg_FbN7MCqGbXSPwxHcGdOg38BDPzdTjsqyE0rFDTF-pZ2qrprnnSnDsq1MnxDsE_CGsk1bdpwBGH6
